### ISSUE TITLE
Clarify that Structured Suffixes Registry is "Specification Required"?

### ISSUE THREAD

**Issue by duerst** [ietf-wg-mediaman/suffixes#16]
There is a discussion about the registration procedure for suffixes. We should cross-check that the registration procedure is clear.

**Comment by duerst** [comment]
Sorry, forgot to say that the discussion was around https://mailarchive.ietf.org/arch/msg/media-types/8-df-mVwr_5f5isy7FwGyT7ei2c/.

**Comment by msporny** [comment]
> We should cross-check that the registration procedure is clear.

I've done a cross-check of the registration procedure for structured suffixes. The guidance given in RFC6838 is:

> The primary guideline for whether a structured type name suffix is registrable is that it be described by a readily available description, preferably within a document published by an established standards-related organization, and for which there's a reference that can be used in a Normative References section of an RFC.

In the [thread referred to above](https://mailarchive.ietf.org/arch/msg/media-types/8-df-mVwr_5f5isy7FwGyT7ei2c/), Amanda asked this question:
> If I'm reading this correctly, this raises another question: at https://www.iana.org/assignments/media-type-structured-suffix, we say that the registration procedure is Expert Review. Should this be listed as Specification Required (which requires both a publicly-available spec and expert review) instead?

AFAICT, Amanda is correct. RFC6838 is clear on the specification requirements for registration of structured suffixes, the registry should be "Specification Required"... not "Expert Review" as it is now.

I also cross-checked all the structured suffix entries and all of them point to a specification, so even though the registry claims that it's "Expert Review"... the registrants and Experts have been operating as if it was "Specification Required" for the past 11 years. :)

> How should we describe the registration procedure for suffixes?

I'm not sure anything needs to change, other than ensuring that the "Registration Procedure" for the structured suffix registry changes to "Specification Required", which is already supported by RFC6838.

What is the process to make that "bug fix" change to the structured suffix registry?

**Comment by msporny** [comment]
Text needs to be added to the specification in an IANA Considerations section requesting that they update the structured suffix registry to note that it is "Specification Required". I will draft a PR that does this.

**Comment by msporny** [comment]
Text has been added to the specification in an IANA Considerations section requesting that IANA update the structured suffix registry to note that it is "Specification Required". This has been done in commit d5703f720fadb29e5aafb9f1c989d14f45c7b4be.

**Comment by msporny** [comment]
IETF 118 outcome: change seems to be fine. Closing.
