### ISSUE TITLE
Document "Compression suffix" pattern

### ISSUE THREAD

**Issue by msporny** [ietf-wg-mediaman/suffixes#27]
Examples of this pattern include "+gzip".

**Comment by msporny** [comment]
From @mnot via the media-types mailing list:
- '+gzip' MUST be the last suffix in a media type that uses it, and the results of unzipping it MUST be a valid instance of the format identified by removing the '+gzip' suffix. That media type MUST also be registered.
- When '+gzip' is present, fragment identifiers are resolved against the decompressed payload, using the resolution scheme of that media type.

**Comment by duerst** [comment]
> From @mnot via the media-types mailing list:
> 
> * '+gzip' MUST be the last suffix

Why "MUST be the last"? Although in general, it doesn't make much sense, one could once more compress the file, leading to something like +gzip+bzip or whatever, or could encrypt or sign it, and so on.

**Comment by mnot** [comment]
@duerst that gets to the heart of it -- do we accidentally want to create a full document processing pipeline model in media type names -- sort of a source routing for formats?

I suspect it's safest to specify constraints like this that can be loosened over time.

**Comment by duerst** [comment]
@mnot I don't want to create a full document processing model. (I'm anyway of the opinion that mime types are descriptive, and that we should mainly talk about "what it is", not about "how to process", but that's a separate issue.)

But I want to avoid artificial barriers that trigger a lot of work in case there's somebody who finds a good use case.

**Comment by msporny** [comment]
This is now documented here: https://datatracker.ietf.org/doc/html/draft-ietf-mediaman-suffixes#name-common-suffix-patterns
