### ISSUE TITLE
Review by @mnot

### ISSUE THREAD

**Issue by msporny** [ietf-wg-mediaman/suffixes#4]
@mnot [wrote](https://mailarchive.ietf.org/arch/msg/media-types/uHkwWAh5nCZqaqsFk8mNppliFvw/):
> Taking a look at this draft, I have a few observations.
>
> In section 2.1, the draft defines a processing module for suffixes, saying that they 'MAY be utilized in a processing pipeline where each segment of the pipeline handles a particular structured syntax suffix by applying decoding rules associated with the structured syntax suffix.'
>
> What's missing here is text that describes the expectations placed upon a suffix definition so that it can be used in such a pipeline -- namely, a defined input and output format, with the implication that a media type can't be registered if there's a mismatch in the processing of the specified suffixes.
> 
> For some (indeed, many) suffixes, such a pipeline model doesn't make much sense. For example, while '+gzip' has a defined input format that leads to a deterministic output format, '+ld' and even '+json' are much less clear in this regard. Perhaps this could be addressed by indicating that such suffixes are merely indicative -- they don't have a place in such pipelines, so content effectively 'passes through' them.
> 
> We should also discuss and perhaps provide guidance about when to define a suffix, as opposed to a top-level media type. So far, registered suffixes have been format conventions and encodings, but with the proposal of '+ld' we seem to be drifting into indicators of a class of use, which seems very top-level-type-y to me.
> 
> Also, will this draft be actually registering any structured suffix combinations? If I read correctly, that's a requirement before a media type using one is registered (and if that reading is correct, it should probably be stated more clearly).

**Comment by msporny** [comment]
> @mnot [wrote](https://mailarchive.ietf.org/arch/msg/media-types/uHkwWAh5nCZqaqsFk8mNppliFvw/):

Hey @mnot, apologies for taking so long to get to this. Been buried for the better part of this year. I'm going to try to summarize the changes to the spec I intend to make based on your review.

>> In section 2.1, the draft defines a processing module for suffixes, saying that they 'MAY be utilized in a processing pipeline where each segment of the pipeline handles a particular structured syntax suffix by applying decoding rules associated with the structured syntax suffix.'
>> What's missing here is text that describes the expectations placed upon a suffix definition so that it can be used in such a pipeline -- namely, a defined input and output format, with the implication that a media type can't be registered if there's a mismatch in the processing of the specified suffixes.

Yes, good observation, and you're right. I added the following in response to your comment, do you find it acceptable (or does more need to be said)?

> [2.1 Processing Multiple Suffixes](https://datatracker.ietf.org/doc/html/draft-ietf-mediaman-suffixes#section-2.1) -- If an application choses to utilize a portion of the media type that is a structured syntax suffix, the specification referred to in the  the "Encoding Considerations" entry of the Structured Syntax Suffixes  Registry ([https://www.iana.org/assignments/media-type-structured-](https://www.iana.org/assignments/media-type-structured-suffix/media-type-structured-suffix.xhtml)   [suffix/media-type-structured-suffix.xhtml](https://www.iana.org/assignments/media-type-structured-suffix/media-type-structured-suffix.xhtml)) MUST be used for both   encoding and decoding the byte stream associated with the media type.

>> For some (indeed, many) suffixes, such a pipeline model doesn't make much sense. For example, while '+gzip' has a defined input format that leads to a deterministic output format, '+ld' and even '+json' are much less clear in this regard. Perhaps this could be addressed by indicating that such suffixes are merely indicative -- they don't have a place in such pipelines, so content effectively 'passes through' them.

Yes, agreed. The current text attempts to say: "If you can lop off the last chunk(s) of a media type, and it has an entry in the structured syntax suffixes table, you can process it using the associated spec." What we don't say right now is: "Keep in mind that you might be left with a media type that has no entry anywhere, and that's fine... you just can't interpret the rest of the media type because it has no associated specification." For example, if you choose to interpret a "application/vc+ld+json" (a Verifiable Credential expressed as JSON-LD) and you choose to interpret it using a JSON-LD processor (by using the `+ld+json` structured suffix)... you'll be left with an `application/vc` "media type" -- which doesn't have an associated media type entry, which means you can't process it further in any sort of pipeline. So, your choices are either process it using a Verifiable Credential processor that understands JSON-LD, or process it more generically using a JSON-LD processor.

I've yet to find a way of saying that in the spec that didn't sound convoluted. Is that a direction that you feel makes sense?

> We should also discuss and perhaps provide guidance about when to define a suffix, as opposed to a top-level media type. So far, registered suffixes have been format conventions and encodings, but with the proposal of '+ld' we seem to be drifting into indicators of a class of use, which seems very top-level-type-y to me.

Yeah, this is where I get to the point where I feel like we should've never listened to the guidance given when registering `application/ld+json`. In theory, `application/ld` is an abstract data model and `application/ld+json` is the JSON-based expression of that abstract data model. We thought it made sense at the time because `application/rdf+xml` followed the same pattern.

We probably should've pushed back and said, "yeah, but media types aren't meant for abstract data models, so, no, we don't want to switch from `application/json-ld` (which is a concrete serialization) to `application/ld+json` (which is a concrete serialization, presumably layered on top of an abstract data model). 

I thought it was strange at the time, but then didn't feel like it was my place to question the way media types are structured, so we just went with the advice. Only later did it come back to bite us when we tried to register `application/did+ld+json`. In an alternate universe, we would've been trying to register `application/did+json-ld` and everything would've been fine (maybe?)... granted, we would've just hit the same issue if we tried `application/did+json-ld+gzip` at some later point in time (again, maybe?).

Is there such a thing as a top-level-type that expresses an abstract data model? A media type used to identify something that doesn't have a syntactic representation? I guess all of those things are top-level types? ... but "Linked Data" feels like it doesn't really need a top-level type. The media-types registry is loaded with examples that seem to indicate that abstract data models are paired with serializations of those data models... For example `application/problem+json`, `application/rdf+xml`, `application/vcard+json`, and others seem to indicate abstract data models sit under many of these representations... and none of them have top-level types.

So, the best advice we might be able to give is: "If your media type has the following structure: ABSTRACT_TYPE + STRUCTURED_SUFFIX + STRUCTURED_SUFFIX, then make sure all the STRUCTURED_SUFFIXes are registered in the Structured Syntax Suffix Registry, and make sure you register the first ABSTRACT_TYPE + STRUCTURED_SUFFIX in the media-type registry. I don't know what sort of guidance we'd give for registering a new top level type, other than -- depend on the media-type folks to have that debate?

>> Also, will this draft be actually registering any structured suffix combinations?

No, the draft isn't supposed to register any structured suffix combinations. We need this draft to exist so that, at a minimum, we can do the following things:

1. Register `+ld+json` and `+ld+cbor` and `+ld+yaml` structured syntax suffixes.
2. Register the `application/did+ld+json` and `application/vc+ld+json` media types.
3. Clarify how we expect folks to interpret those documents as `+json` and `+cbor` and `+yaml`, respectively.

> If I read correctly, that's a requirement before a media type using one is registered (and if that reading is correct, it should probably be stated more clearly).

Yes, agreed. I'll put some language in the spec about that during my next editorial pass.

**Comment by mnot** [comment]
Now I'm wondering if we need a `data/` top level type -- the distinction being that `application/` is for a specific application's consumption, whereas `data/` is more declarative / open.

I suspect that ship may have sailed, though...

Anyway, it looks like you're going in the right direction, thanks!

**Comment by msporny** [comment]
> Now I'm wondering if we need a `data/` top level type -- the distinction being that `application/` is for a specific application's consumption, whereas `data/` is more declarative / open.

I agree, don't know if that ship has sailed. I mean *a* ship has sailed on "application/*"... 

However, looking down the road 20+ years, if we provided a `data` top level type, I could imagine future revisions of specifications deprecating the "application/*" type for "data/*". I know we'd seriously consider that for JSON-LD and Verifiable Credentials. That said, it's a bit of an orthogonal issue... we'd still need to provide guidance on how to handle multiple structured suffixes.

Thanks for the review and the acknowledgement that we're headed in the right direction!

**Comment by TallTed** [comment]
@msporny -- 
> if we tried `application/did+json-ld+gzip`

That just shouldn't exist in any way, shape, or form.

`application/gzip` is the media type of an archive.  There should be no hint of what the *contents* of that archive might be until/unless you de-archive (`ungzip`, here) it, and in this case, find yourself with `application/did+json-ld` (or `application/did+ld+json`, in this universe).

I fear that the media type caretakers have not always been well versed in the ways those things actually work, and have thus accepted and/or advised very broken media types over the years, which are now starting to bite newer registrants.

**Comment by TallTed** [comment]
@mnot —
> Now I'm wondering if we need a `data/` top level type -- the distinction being that `application/` is for a specific application's consumption, whereas `data/` is more declarative / open.

Strong -1.

*Every* registered media type (except those few for executables) would today fall into the `data/` space.  Even those which are "for a specific application's consumption", because no matter what may have been intended at the time those types were registered, data likes to be free, and new/different applications may have been created that consume the documents that were originally created for another application's consumption.

For instance, `application/gzip` was created with intent that `gunzip` would be used to de-archive the contents of that archive — but today, there are dozens if not hundreds of executables that will/can do that job.

**Comment by TallTed** [comment]
@msporny —
> Is there such a thing as a top-level-type that expresses an abstract data model?

No, because media types all apply to documents, i.e., concrete data.

You *might* be able to construct an argument that justifies adding support for abstract media types, in which case I'd suggest `abstract/` as the top level ... but I'd be surprised if such an argument passed muster.

**Comment by mnot** [comment]
@TallTed -- it wasn't a proposal; as I said, that ship has already sailed.

**Comment by msporny** [comment]
> What we don't say right now is: "Keep in mind that you might be left with a media type that has no entry anywhere, and that's fine... you just can't interpret the rest of the media type because it has no associated specification."
> I've yet to find a way of saying that in the spec that didn't sound convoluted. 

Update, we now say this via commit a34bf8cd68968dcc12da85f2687188e5ef534291. I'm not thrilled with the text, it's more verbose than I'd like, but at least it's in there now.

**Comment by msporny** [comment]
@mnot wrote:
> If I read correctly, that's a requirement before a media type using one is registered

We now do this via 818e7b0e6d5d5039dbf196cc25979feb894fb020.

I believe this addresses all your review feedback, @mnot, please let me know if I missed something. Closing (re-open if I missed something).
