### ISSUE TITLE
Review by @TallTed

### ISSUE THREAD

**Issue by msporny** [ietf-wg-mediaman/suffixes#5]
@tallted [wrote](https://mailarchive.ietf.org/arch/msg/media-types/LpZ50A6bqD-mnJ0Zi53gYNasSgU/):
> Regarding https://datatracker.ietf.org/doc/draft-ietf-mediaman-suffixes/
>
> I randomly noticed a typo, here --
> 
>> 2.2.1.  Media Type Fibbing
>> 
>> It is possible for attacker to utilize multiple structured suffixes
>
> -- where "for attacker to" should be either "for attackers to" or "for an attacker to".
>
> As long as I was flagging that, I thought I would read the whole thing over... 
>
> There's another typo here (in section 2.1) --
>> underlying representation according any of the following processing
>
> -- where "according any" should be "according to any".
>
> I think there are substantial errors in the current --
>
>> 2.  Media Types with Multiple Suffixes
>
>-- where the last paragraph preceding 2.1 includes --
>
>> For example, a media type that uses two suffixes, such as
>> "application/foo+xml+gzip" is only permitted insofar as "+gzip" and
>> "+xml" are already registered structured syntax suffixes.
>
> I think the segment below is wrong --
>
>> permitted insofar as "+gzip" and "+xml"
>
> I think that should instead be --
>
>> permitted insofar as "+gzip" and "+xml+gzip"
>
> -- because we're otherwise leaving things open for people to mix any combination of suffixes, even including such things as "+gzip+xml" or "+jpg+gif", which we well know to be nonsense.
>
> Further, as that section provides handling options for consumers of the complex media type "image/svg+xml+gzip", it suggests that 
it is permissible to act on the terminal "+gzip" before looking to the remainder of the type, "image/svg+xml".
>
> While unzipping the original "image/svg+xml+gzip" document does  result in an "image/svg+xml", I do not believe this has anything 
to do with the fallback interpretations which are provided by  media type suffixes -- and which are described in careful detail 
earlier in that paragraph, where it digs into proposed media type  "application/did+ld+json".  Note that one cannot "un-JSON" the 
original document to result in something of the nonexistent  media type "application/did+ld".
>
> I don't have an immediate suggestion for how to fix this, but I feel it absolutely *must* be fixed before this RFC is brought 
to full ratification, and preferably before the current draft expires in August and is replaced by a draft with any other revisions (including fixes of the typos flagged above).

**Comment by msporny** [comment]
@Tallted wrote:
> As long as I was flagging that, I thought I would read the whole thing over...

Thank you for your thorough review, as always, @TallTed! I have fixed the syntax and grammar issues you raised in b1db951993b96976690ce9ed468d5a1e3c51e178.

> I don't have an immediate suggestion for how to fix this, but I feel it absolutely must be fixed before this RFC is brought to full ratification

Well, your observation is correct... it *is* permissible to act on the terminal "+gzip" and not look any further. That's part of the controversy of this specification... that you can end up with media types that are nonsense by just processing using the structured syntax suffix rules. I recently added commit a34bf8cd68968dcc12da85f2687188e5ef534291 that tried to highlight this issue (tracked as issue #7).

I don't know of a way to 1) allow generic processing using structured syntax suffixes, AND 2) avoid this issue. 

The thought experiment I use is the presumptive `application/vc+ld+json` media type... you can process that as `+json` (leaving `application/vc+ld`, which makes no sense), `+ld+json` (leaving `application/vc`, which makes no sense), or `application/vc+ld+json`.

Let me know what you think of the text in a34bf8cd68968dcc12da85f2687188e5ef534291, I think it's the best we can do, but would love to figure out a way to prevent the nonsense media type remainders that can happen as a result of the structured syntax suffix processing rules.

**Comment by TallTed** [comment]
> [@msporny] The thought experiment I use is the presumptive `application/vc+ld+json` media type... you can process that as `+json` (leaving `application/vc+ld`, which makes no sense), `+ld+json` (leaving `application/vc`, which makes no sense), or `application/vc+ld+json`.

The processing alternatives you list make no sense to me.  These do:

* If you understand the full media type `application/vc+ld+json`, you can (obviously) process it as `application/vc+ld+json`.
* If you don't understand the `vc+`, you can fall back to process it as `application/ld+json`, and forget that the `vc+` (which you don't understand and so cannot work with anyway) was there.
* If you don't understand the `ld+`, you can fall back to process it as `application/json`, and forget that the `vc+ld+` (which you don't understand and so cannot work with anyway) was there.

These are also the way that single-plus media types work.

No fall back — neither proposed nor currently in use — would leave the remainder of the media type string as you suggest.

De-archiving/de-compressing things like `application/...+gzip` or `application/...+zip` doesn't generically leave you with the `application/...`, regardless of what was there when you began — though some specific archiving/compressing tools may do so, specifically to those mechanisms, primarily being gzip and its relatives.  This sort of result is not a feature or function of the Media Type system, but rather a feature or function of the archival and/or compression mechanisms.

**Comment by TallTed** [comment]
@msporny --

I think the whole of https://github.com/ietf-wg-mediaman/suffixes/commit/a34bf8cd68968dcc12da85f2687188e5ef534291 is an error.

Processing of Media Types starts with the full type, and falls back to the type which results from deletion of the characters between the left-most `+` and the `/` to its left, including deletion of the `+` but retaining the `/`.

These fall-backs are not _options_ per se, but are meant for "elegant failure", similar to HTML browsers which are supposed to "fail elegantly" when dealing with HTML tags and other elements which the browser doesn't understand or recognize.

**Comment by duerst** [comment]
@TallTed @msporny I had to mull this a few times over, but I think you are both right.

@TallTed's goal is to process the whole of the input as much as possible, with a knowledge of the type that is as precise as possible, more or less in one go. That's why he starts with trying the full type (let's say image/svg+xml+gzip or application/vc+ld+json), and when this type is not known, he falls back to the less precise outside information (image/xml+gzip (not sure that's actually defined; maybe there's a need for an implicit switch from image/xml+gzip to application/xml+gzip) or application/ld+json).

@msporny looks at processing with a pipeline, where e.g. image/svg+xml+gzip is first uncompressed to image/svg+xml, and then parsed into (the imaginary) image/svg, or e.g. application/vc+ld+json is first parsed into (the imaginary) application/vc+ld, and then (the imaginary) application/vc.

When I say imaginary here, I mean that there is no actual MIME document with that type. But there can well be data with that type. A simple example would be the internal data structures of an SVG renderer. If we extend our thought experiment to additional (currently non-existing, and I'm not actually proposing we introduce these :-) types image/svg+json+gzip or image/svg+cbor+..., then it's easily conceivable that these would use the same internal data structures in an SVG renderer.

**Comment by msporny** [comment]
@duerst wrote:
> I had to mull this a few times over, but I think you are both right.

Yes, I'm still mulling this over... and trying to come up with a "processing model" that is logically consistent among all of the existing registered media types and structured suffixes. The thought process I keep going through is:

1. Establish a testable set of structured suffix processing rules.
2. Scan the entire [IANA Media Types registry](https://www.iana.org/assignments/media-types/media-types.xhtml) and the [IANA Structured Suffixes registry](https://www.iana.org/assignments/media-type-structured-suffix/media-type-structured-suffix.xhtml) to see if the rules are logically consistent (no outliers, or the ability to include the outliers in the processing rules).
3. Throw my hands up in frustration and repeat step 1. 

At present, I'm trying to internalize what @TallTed is saying into a processing model and then apply it to the registries above and see if it sticks. I just need to put a few hours aside to do @TallTed's thought exercise against the actual registries.

I'm leaving this issue open until I do so, and then will try and document the results here.

> maybe there's a need for an implicit switch from image/xml+gzip to application/xml+gzip) or application/ld+json).

Yes, and I don't know how to specify this behavior consistently across all media types... at present, I'm not sure it's possible.

> When I say imaginary here, I mean that there is no actual MIME document with that type. But there can well be data with that type. 

Yes, that's how I'm interpreting how media types work at present... is that documented anywhere? I would assume not since, as @TallTed said, media types are for concrete serializations... not abstract data models, even though just about every media type does suggest an abstract data model to the left of any "+suffix".

**Comment by msporny** [comment]
@TallTed I'm closing this issue, largely because we've decided to abandon the "pipeline processing" approach and go with something simpler ("just process the entire suffix, or a subset of the suffix, in order -- you can't mix and match, no more pipelining options, thus reducing complexity by quit a bit"... this is described in the latest spec). 

The latest spec has been been published here:

https://www.ietf.org/archive/id/draft-ietf-mediaman-suffixes-05.html

The sections pertinent to your review comments are here:

https://www.ietf.org/archive/id/draft-ietf-mediaman-suffixes-05.html#section-2

and here:

https://www.ietf.org/archive/id/draft-ietf-mediaman-suffixes-05.html#section-2.1

Please re-review the specification and raise new issues if you see any problems. IETF 117 is next week and we're hoping to enter Last Call shortly thereafter. If you have remaining concerns, please let us know by filing a new issue highlighting the concerns with the -05 draft.

**Comment by TallTed** [comment]
See PR #17. Nothing issue-worthy; just a number of editorial tweaks.
