### ISSUE TITLE
Processing rules need to be deterministic

### ISSUE THREAD

**Issue by alvestrand** [ietf-wg-mediaman/suffixes#7]
The processing rules need to be clear that it is not possible to follow them and end up with an unknown media type.

**Comment by msporny** [comment]
> The processing rules need to be clear that it is not possible to follow them and end up with an unknown media type.

Hmm, but that is possible (and expected).

I've added language here to attempt to more finely highlight this issue (which is unavoidable when you have things like "application/did+ld+json" and "image/svg+xml+gzip": a34bf8cd68968dcc12da85f2687188e5ef534291

Let me know what you think of the new text, or if you were concerned about some other issue.

**Comment by msporny** [comment]
@alvestrand ping again to see if the new text addresses your concern. I plan to close this issue by IETF 116 if I have not received a response by then.

**Comment by msporny** [comment]
> The processing rules need to be clear that it is not possible to follow them and end up with an unknown media type.

The latest -05 specification removes pipeline processing and thus it is not possible to follow the processing rules and end up with an unknown media type. You either process the entire media type, the entire suffix, or a subset of the suffix, once. You can't mix and match anymore, which means you can't end up with an unknown media type. The process has to pick ONE way to process the media type containing a structured suffix.

The latest spec has been been published here:

https://www.ietf.org/archive/id/draft-ietf-mediaman-suffixes-05.html

The sections pertinent to your review comments are here:

https://www.ietf.org/archive/id/draft-ietf-mediaman-suffixes-05.html#section-2

and here:

https://www.ietf.org/archive/id/draft-ietf-mediaman-suffixes-05.html#section-2.1

I'm closing this issue as it seems to be a non-issue now with the -05 draft. Please re-open the issue, or open a new issue if you disagree.
