### ISSUE TITLE
Review from Orie Steele

### ISSUE THREAD

**Issue by msporny** [ietf-wg-mediaman/suffixes#9]
@OR13 wrote:
> Section 2.1 could benefit from some text smithing / list structure.
> Section 2.2 was hard to read initially... An example would help.
> Security considerations section examples could be improved.
> I like the gzip scenario, but are there others?... any concerns related to +jwt / +cwt (being discussed in. RATs now) ?

**Comment by OR13** [comment]
In relation to https://www.ietf.org/archive/id/draft-ietf-mediaman-suffixes-03.html

I can try to tackle some improvement to 2.1 / 2.2.

Hopefully the list engages on the others, otherwise I don't think they need to be addressed.

**Comment by msporny** [comment]
Thanks for the review, @OR13. :) 

> Section 2.1 could benefit from some text smithing / list structure.

Yes, good point. I'll break the numbered items out into lists in a future draft.

> Section 2.2 was hard to read initially... An example would help.

Yeah, that section is problematic. It had to follow the same language that people had copy-pasted into the IANA registry over the past decade (see the "Fragment Identifier Considerations" column).  The proposal is to update those columns to just point to Section 2.2 of the suffixes specification (since that section puts all the copy-pasted text in one place):

https://www.iana.org/assignments/media-type-structured-suffix/media-type-structured-suffix.xhtml

That said, I agree with you, and an example would help. I'll try to add that in the next draft.

I'll have to find an example of each, which will take time. Especially since some of the entries look like they just blindly copied the text instead of checking to see if it actually applied to their media type (like, +gzip and +jwt doesn't actually define fragment identifier resolution in any of the specifications identified, but the registry entry seems to indicate that it does).

> Security considerations section examples could be improved.
> I like the gzip scenario, but are there others?... any concerns related to +jwt / +cwt (being discussed in. RATs now) ?

Honestly, even the +gzip scenario is a bit contrived. We've been asking the group if they know of any attacks against the processing model described, but haven't gotten any strong feelings about what else we should include. I guess we could add one for "If your pipeline processes +jwt, says its "valid"... did it just check the signature and not the `crit` fields? If so, that could be an attack vector?" -- again, I'm stretching there and would appreciate someone with some JWT pipeline processing experience speak to a real world attack that they encountered/know about (if any).

The Security Considerations column in the IANA registry is not great, either -- +der, +ber, +tlv, and +gzip being examples of the sort of "Security Considerations" stuff that shouldn't be placed into a registry.

**Comment by OR13** [comment]
PR for the first item: https://github.com/ietf-wg-mediaman/suffixes/pull/11

**Comment by msporny** [comment]
> Section 2.1 could benefit from some text smithing / list structure.

This was done here:

https://github.com/ietf-wg-mediaman/suffixes/pull/11

> Section 2.2 was hard to read initially... An example would help.

This was done here:

https://github.com/ietf-wg-mediaman/suffixes/pull/14

> Security considerations section examples could be improved.

This was done here:

https://github.com/ietf-wg-mediaman/suffixes/pull/15

> any concerns related to +jwt / +cwt (being discussed in. RATs now) ?

None that jump out at me at present. We can always add/modify the security considerations if something comes up in LC.

Given that the review comments have been addressed (as much as we can right now), I'm closing this issue. Raise a new issue or PR if you feel something else needs to be addressed.
